# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: tensorflow
  version: 2.9.2a0

about:
  home: https://tensorflow.org
  license: Apache License
  summary: 'TensorFlow conda package based on the PyPI wheels.

  For GPU support, install cudatoolkit 11.3.1 and cudnn 8.2.1 which are available as conda packages on the default channel.'

build:
  number: 4

source:
  path: ../

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'

  host:
    - python>=3.10.0,<3.11.0 # Trying python 3.10
    - numpy
    - h5py
    - protobuf
    - certifi
    - importlib-metadata
    - six
    - typing-extensions
    - zipp
    - pip

  run:
    - python>=3.10.0,<3.11.0 # Trying python 3.10
    - numpy
    - h5py
    - protobuf
    - certifi
    - importlib-metadata
    - six
    - typing-extensions
    - zipp
    - pip

test:
  imports:
    - tensorflow